gpt:
  xpaths:
    input_text_elem_xpath: '//*[@id="prompt-textarea"]'
    upload_files_elem_xpath: '//*/form/div/div[2]/div/div/div[1]/div/button[2]'
    upload_local_file_xpath_1: '//div[contains(text(), "Upload from computer")]'
    upload_local_file_xpath_2: '//div[contains(text(), "Upload file")]'
    submit_prompt_btn_xpath: '//button[@data-testid="fruitjuice-send-button"]'
    observed_element_locator_xpath: '[class*="group/conversation-turn"][class*="agent-turn"]'
    turn_menu_item_locator_xpath: './/div[contains(@class, "mt-1") and contains(@class, "flex") and contains(@class, "gap-3") and contains(@class, "empty:hidden") and contains(@class, "juice:-ml-3")]'
    response_block_xpath: './/div[(normalize-space(@class) = "overflow-hidden") or @data-message-author-role="assistant"]'
    plot_images_xpath: |
      .//div[
                        @class = "mb-3 max-w-[80%]"
                    ]

gemini:
  xpaths:
    input_text_elem_xpath: '//*/rich-textarea/div[1]'
    upload_files_elem_xpath_1: '//*/input-area-v2/div/div/div[3]/div/uploader/div[1]/div/button'
    upload_files_elem_xpath_2: '//*/input-area-v2/div/div/div[4]/div/uploader/div[1]/div/button'
    upload_local_file_xpath: '//*[@id="file-uploader-local"]'
    submit_prompt_btn_xpath_1: '//*/input-area-v2/div/div/div[4]/div/div/button'
    submit_prompt_btn_xpath_2: '//*/input-area-v2/div/div/div[3]/div/div/button'
    submit_prompt_btn_xpath_3: '//*/input-area-v2/div/div/div[1]/div/div[1]/rich-textarea/div[1]'
    observed_element_locator_xpath: "[class^='response-container-content']"
    response_footer_locator_xpath: "following-sibling::div[contains(@class, 'response-container-footer')]"
    more_options_menu_element_xpath_1: ".//message-actions/div/div/div[2]/button"
    more_options_menu_element_xpath_2: './/*[@aria-label="Show more options" and @mattooltip="More"]'
    copy_response_xpath: '//*/button[@aria-label="Copy"]'